[project]
name = "simple-investment-portfolio"
version = "0.1.0"
description = "Демонстрационный проект 'Инвестиционный портфель', написанный на Django"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.3",
]
