# Generated by Django 5.2.3 on 2025-07-03 01:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investment_portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InvestmentPortfolio",
            new_name="InvestmentPortfolioModel",
        ),
        migrations.CreateModel(
            name="InvestmentAssetModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investment_portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investment_portfolio.investmentportfoliomodel",
                    ),
                ),
            ],
            options={
                "db_table": "investment_portfolio__investment_assets",
                "db_table_comment": "Активы инвестиционного портфеля",
            },
        ),
    ]
