# Generated by Django 5.2.3 on 2025-07-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investment_portfolio", "0003_investmentportfoliomodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentassetmodel",
            name="name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investmentassetmodel",
            name="ticket",
            field=models.CharField(default="test", max_length=20),
            preserve_default=False,
        ),
    ]
