# Generated by Django 5.2.3 on 2025-07-04 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investment_portfolio", "0004_investmentassetmodel_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentassetmodel",
            name="investment_portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="investment_portfolio.investmentportfoliomodel",
            ),
        ),
    ]
